# Generated by Django 2.2 on 2019-10-25 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='img/user_avatar/', verbose_name='Foto perfil')),
                ('profile_cover', models.ImageField(blank=True, null=True, upload_to='img/user_cover/', verbose_name='Cover profile')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Sobrenome')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografia')),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Nacionalidade')),
                ('email', models.CharField(max_length=254, verbose_name='E-mail')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('you_tube', models.URLField(blank=True, verbose_name='YouTube')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
