# Generated by Django 2.2 on 2019-10-25 13:29

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_board', models.ImageField(blank=True, null=True, upload_to='img/board/', verbose_name='Foto para fundo!')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_sport', models.CharField(max_length=100, unique=True, verbose_name='Defina uma categoria de esporte para sua experiência!')),
                ('category_published', models.DateTimeField(auto_now_add=True)),
                ('author_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_title', models.CharField(max_length=150, unique=True)),
                ('experience_equipment', models.BooleanField(choices=[(None, ''), (True, 'Sim'), (False, 'Não')], default=None, max_length=3, verbose_name='Precisa de algum equipamento?')),
                ('experience_people', models.PositiveIntegerField(verbose_name='Quantas pessoas podem realizar a atividade?')),
                ('experience_supervisor', models.BooleanField(choices=[(None, ''), (True, 'Sim'), (False, 'Não')], default=None, max_length=3, verbose_name='O anfitrião precisa acompanhar durante a atividade?')),
                ('experience_difficulty', models.CharField(choices=[(None, ''), ('1', 'Facil'), ('2', 'Medio'), ('3', 'Dificil'), ('4', 'Expert')], default=None, max_length=1, verbose_name='Qual nivel de dificuldade?')),
                ('experience_age', models.PositiveIntegerField(verbose_name='Qual idade minima?')),
                ('experience_pet', models.BooleanField(choices=[(None, ''), (True, 'Sim'), (False, 'Não')], default=None, max_length=3, verbose_name='Animais de estimação são bem vindos?')),
                ('experience_duration', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Qual tempo de duração?')),
                ('experience_duration_method', models.CharField(choices=[('mi', 'Minuto'), ('ho', 'Hora'), ('di', 'Dia'), ('se', 'Semana')], default=None, max_length=2, verbose_name='')),
                ('experience_value', models.BooleanField(choices=[(None, ''), (True, 'Sim'), (False, 'Não')], default=None, max_length=3, verbose_name='A experiencia é cobrada?')),
                ('experience_published', models.DateTimeField(auto_now_add=True)),
                ('experience_description', models.CharField(max_length=800, verbose_name='Descreva a experiência!')),
                ('author_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_sport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.CategorySportModel', verbose_name='category')),
            ],
            options={
                'verbose_name': 'experience',
                'verbose_name_plural': 'experiences',
            },
        ),
        migrations.CreateModel(
            name='ExperiencePriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Qual valor?')),
                ('experience_price_method', models.CharField(choices=[(None, ''), ('pe', 'Por pessoa'), ('ac', 'Por atividade'), ('hp', 'Por hora/pessoa'), ('ha', 'Por hora/atividade')], default=None, max_length=2, verbose_name='Como é cobrado?')),
                ('experience', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='e_prices', to='board.ExperienceModel')),
            ],
            options={
                'verbose_name': 'e_price',
                'verbose_name_plural': 'e_prices',
            },
        ),
        migrations.CreateModel(
            name='ExperiencePhotoGalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_photo', models.ImageField(blank=True, null=True, upload_to='img/experience/', verbose_name='Adicione fotos a experiência!')),
                ('photo_published', models.DateTimeField(auto_now_add=True)),
                ('author_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='e_photos', to='board.ExperienceModel')),
            ],
            options={
                'verbose_name': 'e_photo',
                'verbose_name_plural': 'e_photos',
            },
        ),
        migrations.CreateModel(
            name='ExperienceMeetPointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('e_address', models.CharField(max_length=100)),
                ('e_city', models.CharField(max_length=50)),
                ('experience', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='e_locations', to='board.ExperienceModel')),
            ],
            options={
                'verbose_name': 'e_location',
                'verbose_name_plural': 'e_locations',
            },
        ),
        migrations.CreateModel(
            name='ExperienceCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_description', models.CharField(max_length=500, verbose_name='Descreva seu comentario!')),
                ('comment_star', models.CharField(choices=[(None, ''), ('1', 'Pessima'), ('2', 'Ruim'), ('3', 'Mais ou menos'), ('4', 'Bom'), ('5', 'Maravilha')], default='5', max_length=1, verbose_name='Qual sua avalição?')),
                ('comment_published', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='e_comments', to='board.ExperienceModel')),
            ],
            options={
                'verbose_name': 'e_comment',
                'verbose_name_plural': 'e_comments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_title', models.CharField(max_length=150, verbose_name='Nome do equipamento:')),
                ('equipment_availability', models.BooleanField(choices=[(None, ''), (True, 'Sim'), (False, 'Não')], default=None, max_length=3, verbose_name='Você disponibiliza o equipamento?')),
                ('equipment_picture', models.ImageField(blank=True, null=True, upload_to='img/equipment/', verbose_name='Uma imagem do equipamento!')),
                ('equipment_description', models.CharField(blank=True, max_length=800, null=True, verbose_name='Descreva o equipamento!')),
                ('experience', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='equipments', to='board.ExperienceModel')),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipments',
            },
        ),
    ]
