# Generated by Django 2.2 on 2019-11-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20191108_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencemodel',
            name='experience_equipment',
            field=models.BooleanField(default=None, verbose_name='Precisa de algum equipamento?'),
        ),
    ]
