# Generated by Django 2.2 on 2019-11-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20191129_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencephotogallerymodel',
            name='experience_photo',
            field=models.FileField(blank=True, null=True, upload_to='img/experience/', verbose_name='Adicione fotos a experiência!'),
        ),
    ]
