# Generated by Django 2.2 on 2019-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20191130_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencephotogallerymodel',
            name='experience_photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/experience/', verbose_name='Adicione fotos a experiência!'),
        ),
    ]
