# Generated by Django 2.2 on 2019-12-05 22:09

import board.templatetags.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20191130_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencephotogallerymodel',
            name='experience_photo',
            field=models.FileField(blank=True, null=True, upload_to='img/experience/', validators=[board.templatetags.validators.validate_file_extension], verbose_name='Adicione fotos a experiência!'),
        ),
    ]
